# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Sat Aug 10 14:02:14 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1390, 859)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidgetMainWindow = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetMainWindow.setObjectName(_fromUtf8("tabWidgetMainWindow"))
        self.tabDirectory = QtGui.QWidget()
        self.tabDirectory.setObjectName(_fromUtf8("tabDirectory"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabDirectory)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelDirectoryLabel = QtGui.QLabel(self.tabDirectory)
        self.labelDirectoryLabel.setObjectName(_fromUtf8("labelDirectoryLabel"))
        self.horizontalLayout_3.addWidget(self.labelDirectoryLabel)
        self.labelDirectory = QtGui.QLabel(self.tabDirectory)
        self.labelDirectory.setText(_fromUtf8(""))
        self.labelDirectory.setObjectName(_fromUtf8("labelDirectory"))
        self.horizontalLayout_3.addWidget(self.labelDirectory)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.treeViewDirectory = QtGui.QTreeView(self.tabDirectory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeViewDirectory.sizePolicy().hasHeightForWidth())
        self.treeViewDirectory.setSizePolicy(sizePolicy)
        self.treeViewDirectory.setObjectName(_fromUtf8("treeViewDirectory"))
        self.gridLayout_2.addWidget(self.treeViewDirectory, 1, 0, 1, 1)
        self.tabWidgetMainWindow.addTab(self.tabDirectory, _fromUtf8(""))
        self.tabData = QtGui.QWidget()
        self.tabData.setObjectName(_fromUtf8("tabData"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabData)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelDataArtist = QtGui.QLabel(self.tabData)
        self.labelDataArtist.setObjectName(_fromUtf8("labelDataArtist"))
        self.gridLayout_3.addWidget(self.labelDataArtist, 0, 0, 1, 1)
        self.lineEditDataArtist = QtGui.QLineEdit(self.tabData)
        self.lineEditDataArtist.setEnabled(True)
        self.lineEditDataArtist.setReadOnly(True)
        self.lineEditDataArtist.setObjectName(_fromUtf8("lineEditDataArtist"))
        self.gridLayout_3.addWidget(self.lineEditDataArtist, 0, 1, 1, 1)
        self.lineEditDataTitle = QtGui.QLineEdit(self.tabData)
        self.lineEditDataTitle.setEnabled(True)
        self.lineEditDataTitle.setReadOnly(True)
        self.lineEditDataTitle.setObjectName(_fromUtf8("lineEditDataTitle"))
        self.gridLayout_3.addWidget(self.lineEditDataTitle, 1, 1, 1, 1)
        self.labelDataTitle = QtGui.QLabel(self.tabData)
        self.labelDataTitle.setObjectName(_fromUtf8("labelDataTitle"))
        self.gridLayout_3.addWidget(self.labelDataTitle, 1, 0, 1, 1)
        self.labelDataDate = QtGui.QLabel(self.tabData)
        self.labelDataDate.setObjectName(_fromUtf8("labelDataDate"))
        self.gridLayout_3.addWidget(self.labelDataDate, 2, 0, 1, 1)
        self.lineEditDataDate = QtGui.QLineEdit(self.tabData)
        self.lineEditDataDate.setEnabled(True)
        self.lineEditDataDate.setReadOnly(True)
        self.lineEditDataDate.setObjectName(_fromUtf8("lineEditDataDate"))
        self.gridLayout_3.addWidget(self.lineEditDataDate, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidgetData = QtGui.QTabWidget(self.tabData)
        self.tabWidgetData.setObjectName(_fromUtf8("tabWidgetData"))
        self.tabData_2 = QtGui.QWidget()
        self.tabData_2.setObjectName(_fromUtf8("tabData_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabData_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonFiles = QtGui.QRadioButton(self.tabData_2)
        self.radioButtonFiles.setObjectName(_fromUtf8("radioButtonFiles"))
        self.horizontalLayout_4.addWidget(self.radioButtonFiles)
        self.radioButtonTags = QtGui.QRadioButton(self.tabData_2)
        self.radioButtonTags.setChecked(True)
        self.radioButtonTags.setObjectName(_fromUtf8("radioButtonTags"))
        self.horizontalLayout_4.addWidget(self.radioButtonTags)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(902, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.tableViewDataTags = QtGui.QTableView(self.tabData_2)
        self.tableViewDataTags.setEnabled(True)
        self.tableViewDataTags.setObjectName(_fromUtf8("tableViewDataTags"))
        self.gridLayout_5.addWidget(self.tableViewDataTags, 1, 0, 1, 2)
        self.tabWidgetData.addTab(self.tabData_2, _fromUtf8(""))
        self.tabDataFree = QtGui.QWidget()
        self.tabDataFree.setObjectName(_fromUtf8("tabDataFree"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabDataFree)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.kledNumberOfTracks = KLed(self.tabDataFree)
        self.kledNumberOfTracks.setShape(KLed.Circular)
        self.kledNumberOfTracks.setColor(QtGui.QColor(255, 0, 0))
        self.kledNumberOfTracks.setObjectName(_fromUtf8("kledNumberOfTracks"))
        self.horizontalLayout_5.addWidget(self.kledNumberOfTracks)
        self.labelNumberOfTracksLabel = QtGui.QLabel(self.tabDataFree)
        self.labelNumberOfTracksLabel.setObjectName(_fromUtf8("labelNumberOfTracksLabel"))
        self.horizontalLayout_5.addWidget(self.labelNumberOfTracksLabel)
        self.labelNumberOfTracks = QtGui.QLabel(self.tabDataFree)
        self.labelNumberOfTracks.setObjectName(_fromUtf8("labelNumberOfTracks"))
        self.horizontalLayout_5.addWidget(self.labelNumberOfTracks)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.textEditDataFree = QtGui.QTextEdit(self.tabDataFree)
        self.textEditDataFree.setObjectName(_fromUtf8("textEditDataFree"))
        self.gridLayout_4.addWidget(self.textEditDataFree, 1, 0, 1, 1)
        self.tabWidgetData.addTab(self.tabDataFree, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidgetData, 1, 0, 1, 1)
        self.tabWidgetMainWindow.addTab(self.tabData, _fromUtf8(""))
        self.tabFinal = QtGui.QWidget()
        self.tabFinal.setObjectName(_fromUtf8("tabFinal"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabFinal)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkBoxArtist = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxArtist.setChecked(False)
        self.checkBoxArtist.setObjectName(_fromUtf8("checkBoxArtist"))
        self.gridLayout_7.addWidget(self.checkBoxArtist, 0, 0, 1, 1)
        self.lineEditFinalArtist = QtGui.QLineEdit(self.tabFinal)
        self.lineEditFinalArtist.setDragEnabled(True)
        self.lineEditFinalArtist.setObjectName(_fromUtf8("lineEditFinalArtist"))
        self.gridLayout_7.addWidget(self.lineEditFinalArtist, 0, 1, 1, 1)
        self.pushButtonArtistApplyRules = QtGui.QPushButton(self.tabFinal)
        self.pushButtonArtistApplyRules.setObjectName(_fromUtf8("pushButtonArtistApplyRules"))
        self.gridLayout_7.addWidget(self.pushButtonArtistApplyRules, 0, 2, 1, 1)
        self.checkBoxTitle = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxTitle.setChecked(False)
        self.checkBoxTitle.setObjectName(_fromUtf8("checkBoxTitle"))
        self.gridLayout_7.addWidget(self.checkBoxTitle, 1, 0, 1, 1)
        self.lineEditFinalTitle = QtGui.QLineEdit(self.tabFinal)
        self.lineEditFinalTitle.setObjectName(_fromUtf8("lineEditFinalTitle"))
        self.gridLayout_7.addWidget(self.lineEditFinalTitle, 1, 1, 1, 1)
        self.pushButtonTitleApplyRules = QtGui.QPushButton(self.tabFinal)
        self.pushButtonTitleApplyRules.setObjectName(_fromUtf8("pushButtonTitleApplyRules"))
        self.gridLayout_7.addWidget(self.pushButtonTitleApplyRules, 1, 2, 1, 1)
        self.checkBoxDate = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxDate.setChecked(False)
        self.checkBoxDate.setObjectName(_fromUtf8("checkBoxDate"))
        self.gridLayout_7.addWidget(self.checkBoxDate, 2, 0, 1, 1)
        self.lineEditFinalDate = QtGui.QLineEdit(self.tabFinal)
        self.lineEditFinalDate.setObjectName(_fromUtf8("lineEditFinalDate"))
        self.gridLayout_7.addWidget(self.lineEditFinalDate, 2, 1, 1, 1)
        self.pushButtonDateApplyRules = QtGui.QPushButton(self.tabFinal)
        self.pushButtonDateApplyRules.setObjectName(_fromUtf8("pushButtonDateApplyRules"))
        self.gridLayout_7.addWidget(self.pushButtonDateApplyRules, 2, 2, 1, 1)
        self.checkBoxComment = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxComment.setObjectName(_fromUtf8("checkBoxComment"))
        self.gridLayout_7.addWidget(self.checkBoxComment, 3, 0, 1, 1)
        self.lineEditFinalComment = QtGui.QLineEdit(self.tabFinal)
        self.lineEditFinalComment.setObjectName(_fromUtf8("lineEditFinalComment"))
        self.gridLayout_7.addWidget(self.lineEditFinalComment, 3, 1, 1, 1)
        self.pushButtonCommentApplyRules = QtGui.QPushButton(self.tabFinal)
        self.pushButtonCommentApplyRules.setObjectName(_fromUtf8("pushButtonCommentApplyRules"))
        self.gridLayout_7.addWidget(self.pushButtonCommentApplyRules, 3, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabFinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8.addWidget(self.groupBox, 0, 1, 4, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBoxVariousArtists = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxVariousArtists.setObjectName(_fromUtf8("checkBoxVariousArtists"))
        self.horizontalLayout_2.addWidget(self.checkBoxVariousArtists)
        self.checkBoxContinuousNumbering = QtGui.QCheckBox(self.tabFinal)
        self.checkBoxContinuousNumbering.setObjectName(_fromUtf8("checkBoxContinuousNumbering"))
        self.horizontalLayout_2.addWidget(self.checkBoxContinuousNumbering)
        self.line = QtGui.QFrame(self.tabFinal)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.label = QtGui.QLabel(self.tabFinal)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBoxDisk = QtGui.QComboBox(self.tabFinal)
        self.comboBoxDisk.setObjectName(_fromUtf8("comboBoxDisk"))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.setItemText(0, _fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.comboBoxDisk.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBoxDisk)
        spacerItem2 = QtGui.QSpacerItem(698, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tableViewFinal = QtGui.QTableView(self.tabFinal)
        self.tableViewFinal.setObjectName(_fromUtf8("tableViewFinal"))
        self.gridLayout_8.addWidget(self.tableViewFinal, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(1077, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButtonSave = QtGui.QPushButton(self.tabFinal)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.tabWidgetMainWindow.addTab(self.tabFinal, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidgetMainWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1390, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTreeViewDirectoryClicked = QtGui.QAction(MainWindow)
        self.actionTreeViewDirectoryClicked.setObjectName(_fromUtf8("actionTreeViewDirectoryClicked"))
        self.actionRadioButtonsToggle = QtGui.QAction(MainWindow)
        self.actionRadioButtonsToggle.setObjectName(_fromUtf8("actionRadioButtonsToggle"))
        self.actionTabChanged = QtGui.QAction(MainWindow)
        self.actionTabChanged.setObjectName(_fromUtf8("actionTabChanged"))
        self.actionTabDataChanged = QtGui.QAction(MainWindow)
        self.actionTabDataChanged.setObjectName(_fromUtf8("actionTabDataChanged"))
        self.actionSaveButtonClicked = QtGui.QAction(MainWindow)
        self.actionSaveButtonClicked.setObjectName(_fromUtf8("actionSaveButtonClicked"))
        self.actionCheckBoxDataChanged = QtGui.QAction(MainWindow)
        self.actionCheckBoxDataChanged.setObjectName(_fromUtf8("actionCheckBoxDataChanged"))
        self.actionLineEditChanged = QtGui.QAction(MainWindow)
        self.actionLineEditChanged.setObjectName(_fromUtf8("actionLineEditChanged"))
        self.actionFreeDataTextChanged = QtGui.QAction(MainWindow)
        self.actionFreeDataTextChanged.setObjectName(_fromUtf8("actionFreeDataTextChanged"))

        self.retranslateUi(MainWindow)
        self.tabWidgetMainWindow.setCurrentIndex(2)
        self.tabWidgetData.setCurrentIndex(0)
        QtCore.QObject.connect(self.tabWidgetMainWindow, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.actionTabChanged.trigger)
        QtCore.QObject.connect(self.treeViewDirectory, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), self.actionTreeViewDirectoryClicked.trigger)
        QtCore.QObject.connect(self.tabWidgetData, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.actionTabDataChanged.trigger)
        QtCore.QObject.connect(self.radioButtonTags, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionTabDataChanged.trigger)
        QtCore.QObject.connect(self.radioButtonFiles, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionTabDataChanged.trigger)
        QtCore.QObject.connect(self.pushButtonSave, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSaveButtonClicked.trigger)
        QtCore.QObject.connect(self.checkBoxArtist, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QObject.connect(self.checkBoxTitle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QObject.connect(self.checkBoxDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QObject.connect(self.lineEditFinalArtist, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.actionLineEditChanged.trigger)
        QtCore.QObject.connect(self.lineEditFinalTitle, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.actionLineEditChanged.trigger)
        QtCore.QObject.connect(self.lineEditFinalDate, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.actionLineEditChanged.trigger)
        QtCore.QObject.connect(self.lineEditFinalComment, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.actionLineEditChanged.trigger)
        QtCore.QObject.connect(self.checkBoxComment, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QObject.connect(self.textEditDataFree, QtCore.SIGNAL(_fromUtf8("textChanged()")), self.actionFreeDataTextChanged.trigger)
        QtCore.QObject.connect(self.checkBoxVariousArtists, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QObject.connect(self.checkBoxContinuousNumbering, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCheckBoxDataChanged.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelDirectoryLabel.setText(_translate("MainWindow", "Directory: ", None))
        self.tabWidgetMainWindow.setTabText(self.tabWidgetMainWindow.indexOf(self.tabDirectory), _translate("MainWindow", "Directory", None))
        self.labelDataArtist.setText(_translate("MainWindow", "Artist", None))
        self.labelDataTitle.setText(_translate("MainWindow", "Title", None))
        self.labelDataDate.setText(_translate("MainWindow", "Date", None))
        self.radioButtonFiles.setText(_translate("MainWindow", "Files", None))
        self.radioButtonTags.setText(_translate("MainWindow", "Tags", None))
        self.tabWidgetData.setTabText(self.tabWidgetData.indexOf(self.tabData_2), _translate("MainWindow", "Data", None))
        self.labelNumberOfTracksLabel.setText(_translate("MainWindow", "Number of tracks:", None))
        self.labelNumberOfTracks.setText(_translate("MainWindow", "000", None))
        self.tabWidgetData.setTabText(self.tabWidgetData.indexOf(self.tabDataFree), _translate("MainWindow", "Free", None))
        self.tabWidgetMainWindow.setTabText(self.tabWidgetMainWindow.indexOf(self.tabData), _translate("MainWindow", "Data", None))
        self.checkBoxArtist.setText(_translate("MainWindow", "Artist", None))
        self.pushButtonArtistApplyRules.setText(_translate("MainWindow", "Apply rules", None))
        self.checkBoxTitle.setText(_translate("MainWindow", "Titel", None))
        self.pushButtonTitleApplyRules.setText(_translate("MainWindow", "Apply rules", None))
        self.checkBoxDate.setText(_translate("MainWindow", "Date", None))
        self.pushButtonDateApplyRules.setText(_translate("MainWindow", "Apply rules", None))
        self.checkBoxComment.setText(_translate("MainWindow", "Comment", None))
        self.pushButtonCommentApplyRules.setText(_translate("MainWindow", "Apply rules", None))
        self.groupBox.setTitle(_translate("MainWindow", "Rules", None))
        self.checkBoxVariousArtists.setText(_translate("MainWindow", "Various Artists", None))
        self.checkBoxContinuousNumbering.setText(_translate("MainWindow", "Continuous numbering", None))
        self.label.setText(_translate("MainWindow", "Volume:", None))
        self.comboBoxDisk.setItemText(1, _translate("MainWindow", "disk 1", None))
        self.comboBoxDisk.setItemText(2, _translate("MainWindow", "disk 2", None))
        self.comboBoxDisk.setItemText(3, _translate("MainWindow", "disk 3", None))
        self.comboBoxDisk.setItemText(4, _translate("MainWindow", "disk 4", None))
        self.comboBoxDisk.setItemText(5, _translate("MainWindow", "disk 5", None))
        self.comboBoxDisk.setItemText(6, _translate("MainWindow", "disk 6", None))
        self.comboBoxDisk.setItemText(7, _translate("MainWindow", "disk 7", None))
        self.comboBoxDisk.setItemText(8, _translate("MainWindow", "disk 8", None))
        self.comboBoxDisk.setItemText(9, _translate("MainWindow", "disk 9", None))
        self.comboBoxDisk.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBoxDisk.setItemText(11, _translate("MainWindow", "B", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Save", None))
        self.tabWidgetMainWindow.setTabText(self.tabWidgetMainWindow.indexOf(self.tabFinal), _translate("MainWindow", "Final", None))
        self.actionTreeViewDirectoryClicked.setText(_translate("MainWindow", "treeViewDirectoryClicked", None))
        self.actionRadioButtonsToggle.setText(_translate("MainWindow", "radioButtonsToggle", None))
        self.actionTabChanged.setText(_translate("MainWindow", "tabChanged", None))
        self.actionTabDataChanged.setText(_translate("MainWindow", "tabDataChanged", None))
        self.actionSaveButtonClicked.setText(_translate("MainWindow", "saveButtonClicked", None))
        self.actionCheckBoxDataChanged.setText(_translate("MainWindow", "checkBoxDataChanged", None))
        self.actionLineEditChanged.setText(_translate("MainWindow", "lineEditChanged", None))
        self.actionFreeDataTextChanged.setText(_translate("MainWindow", "FreeDataTextChanged", None))
        self.actionFreeDataTextChanged.setToolTip(_translate("MainWindow", "FreeDataTextChanged", None))

from PyKDE4.kdeui import KLed
